@Gateway_HostAddress = http://localhost:8888

POST {{Gateway_HostAddress}}/api/products/diagnostics/consumer-exception-policy/timeout

###

POST {{Gateway_HostAddress}}/api/products/diagnostics/consumer-exception-policy/unhandled
