<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <IsTestProject>true</IsTestProject>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="10.0.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.10.0" />
    <PackageReference Include="Npgsql" Version="10.0.3" />
    <PackageReference Include="NSubstitute" Version="6.2.0" />
    <PackageReference Include="Shouldly" Version="4.3.0" />
    <PackageReference Include="WolverineFx" Version="6.36.0" />
    <PackageReference Include="xunit.v3.mtp-off" Version="4.0.0" />
    <PackageReference Include="xunit.runner.visualstudio" Version="4.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
    <Content Include="..\..\docker-compose\sql-script\create_inventoryitems_table.sql" Link="Schema\inventory.sql" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\BC-Contracts\Lab.BoundedContextContracts.Inventory\Lab.BoundedContextContracts.Inventory.csproj" />
    <ProjectReference Include="..\..\src\BuildingBlocks\Lab.BuildingBlocks.Integrations\Lab.BuildingBlocks.Integrations.csproj" />
    <ProjectReference Include="..\..\src\Inventory\DomainCore\InventoryControl.Applications\InventoryControl.Applications.csproj" />
    <ProjectReference Include="..\..\src\Inventory\DomainCore\InventoryControl.Domains\InventoryControl.Domains.csproj" />
    <ProjectReference Include="..\..\src\Inventory\DomainCore\InventoryControl.Infrastructure\InventoryControl.Infrastructure.csproj" />
  </ItemGroup>

</Project>
