FROM mcr.microsoft.com/dotnet/sdk:10.0
WORKDIR /workspace
COPY MQArchLab.slnx global.json ./
COPY src/ ./src/
COPY tests/ ./tests/
COPY docker-compose/sql-script/ ./docker-compose/sql-script/
RUN dotnet restore MQArchLab.slnx --disable-parallel \
    && dotnet build MQArchLab.slnx -c Release --no-restore --disable-build-servers -m:1
ENTRYPOINT ["dotnet", "test", "MQArchLab.slnx", "-c", "Release", "--no-build", "--no-restore", "-m:1", "--logger", "trx", "--results-directory", "/results"]
