server:
  http_listen_port: 3200

distributor:
  receivers:
    otlp:
      protocols:
        http: {}
        grpc: {}

ingester:
  max_block_bytes: 1000000
  trace_idle_period: 10s

compactor:
  compaction:
    block_retention: 1h

storage:
  trace:
    backend: local
    wal:
      path: /tmp/tempo/wal
    local:
      path: /tmp/tempo/blocks

