CREATE TABLE IF NOT EXISTS Products (
    Id UUID PRIMARY KEY,
    Name VARCHAR(255) NOT NULL,
    Description TEXT,
    Price NUMERIC(18, 2) NOT NULL,
    IsDeleted BOOLEAN NOT NULL DEFAULT FALSE,
    Version INT NOT NULL DEFAULT 1
);