<script setup lang="ts">
import { onMounted, onUnmounted, ref, watch } from 'vue'
import { ApiError, changeStock, inventory, products, stockInt, type InventoryStock, type Product } from '../api'
const list = ref<Product[]>([]), selected = ref(''), stock = ref<InventoryStock | null>(null), amount = ref(0), action = ref<'initialize'|'increase'|'decrease'|'restock'>('increase')
const listLoading = ref(false), loading = ref(false), busy = ref(false), listError = ref(''), error = ref(''), actionError = ref(''), message = ref(''), uncertain = ref(false)
let listController: AbortController | undefined, stockController: AbortController | undefined
async function loadProducts() { listController?.abort(); const current = listController = new AbortController(); listLoading.value = true; listError.value = ''; try { const result = await products(current.signal); if (!current.signal.aborted) list.value = result } catch (e) { if (!current.signal.aborted) listError.value = (e as Error).message } finally { if (listController === current) listLoading.value = false } }
async function loadStock() { stockController?.abort(); stock.value = null; error.value = ''; message.value = ''; if (!selected.value) { loading.value = false; return } const current = stockController = new AbortController(); loading.value = true; try { const result = await inventory(selected.value, current.signal); if (!current.signal.aborted) stock.value = result } catch (e) { if (!current.signal.aborted) error.value = (e as Error).message } finally { if (stockController === current) loading.value = false } }
watch(selected, () => { uncertain.value = false; actionError.value = ''; loadStock() }); onMounted(loadProducts); onUnmounted(() => { listController?.abort(); stockController?.abort() })
async function submit() { if (busy.value || uncertain.value || !selected.value) return; actionError.value = ''; message.value = ''; if (!stockInt(amount.value)) { actionError.value = '請輸入 0 至 2,147,483,647 的整數。'; return } if (action.value !== 'initialize' && amount.value === 0) { actionError.value = '調整數量須大於 0。'; return } busy.value = true; try { await changeStock(selected.value, action.value, amount.value); await loadStock(); message.value = '已送出，顯示服務最新庫存。' } catch (e) { actionError.value = (e as Error).message; uncertain.value = e instanceof ApiError && e.uncertain } finally { busy.value = false } }
</script>
<template><div class="page"><div class="page-heading"><div><span class="eyebrow accent">INVENTORY OPERATIONS</span><h1>庫存作業</h1><p>先選商品並查詢服務資料；未取得庫存時不推定為零。</p></div></div>
    <div class="two-column"><section class="panel"><div class="panel-heading"><div><span class="eyebrow accent">01 / SELECT PRODUCT</span><h2>選擇商品</h2></div><button class="text-button" type="button" :disabled="listLoading" @click="loadProducts">更新清單</button></div><label for="stock-product">商品</label><select id="stock-product" v-model="selected" :disabled="busy"><option value="">請選擇商品</option><option v-for="p in list" :key="p.id" :value="p.id">{{ p.name }} · {{ p.id.slice(0, 8) }}</option></select><p v-if="listError" class="notice error" role="alert">{{ listError }} <button type="button" @click="loadProducts">重試</button></p><p v-else-if="listLoading" class="hint" role="status">商品讀取中…</p><p v-else-if="!list.length" class="hint">目前沒有商品可供選擇。</p>
    <div class="stock-status"><span class="eyebrow">AVAILABLE STOCK</span><strong v-if="stock && !loading">{{ stock.availableQuantity }} <small>件</small></strong><strong v-else>—</strong><p v-if="stock">服務目前回傳的可用數量</p><p v-else-if="selected">庫存尚未確認</p><p v-else>選擇商品後查詢</p></div><button class="button button-secondary full" type="button" :disabled="!selected || loading" @click="loadStock">{{ loading ? '查詢中…' : '查詢最新庫存' }}</button><p v-if="error" class="notice error" role="alert">{{ error }}<br>如需建立庫存，請由作業員明確選擇「初始化」；此錯誤不表示庫存為零。</p></section>
    <section class="panel"><span class="eyebrow accent">02 / STOCK ACTION</span><h2>調整庫存</h2><p class="muted">選擇明確的動作。退貨回補與增加都會把數量加到現有庫存。</p><form @submit.prevent="submit"><label for="stock-action">作業類型</label><select id="stock-action" v-model="action" :disabled="busy || uncertain"><option value="initialize">初始化（建立初始數量）</option><option value="increase">增加庫存（加上數量）</option><option value="decrease">扣除庫存（減去數量）</option><option value="restock">退貨回補（增加庫存）</option></select><label for="stock-amount">{{ action === 'initialize' ? '初始數量' : '調整數量' }}</label><input id="stock-amount" v-model.number="amount" type="number" min="0" max="2147483647" step="1" required :disabled="busy || uncertain"/><p class="hint">初始化只由作業員明確操作。每次寫入完成後重新讀取服務庫存。</p><p v-if="actionError" class="notice" :class="uncertain ? 'warning' : 'error'" role="alert">{{ actionError }}<span v-if="uncertain"> 請先查詢最新庫存，評估結果後才建立新作業。</span></p><p v-if="message" class="notice success" role="status">{{ message }}</p><button class="button button-primary full" type="submit" :disabled="!selected || busy || uncertain || !stockInt(amount) || (action !== 'initialize' && !stock)">{{ busy ? '送出中…' : '確認送出' }}</button><button v-if="uncertain" class="button button-secondary full" type="button" @click="uncertain = false; actionError = '已選擇新作業；請確認目前庫存與數量。'">我已查核，建立新作業</button></form></section></div>
</div></template>
