<script setup lang="ts">
import { computed, onMounted, onUnmounted, ref, watch } from 'vue'
import { useRouter } from 'vue-router'
import { ApiError, createPurchase, money, moneyValid, newId, positiveInt, products, purchases, quote, skuValid, type Product, type Provider, type PurchaseIdentity, type PurchaseOrder, type Quote } from '../api'
const router = useRouter(), list = ref<Product[]>([]), rows = ref<PurchaseOrder[]>([]), selected = ref(''), provider = ref<Provider>('direct'), sku = ref('REAL-001'), quantity = ref(1), unitPrice = ref(0), currentQuote = ref<Quote | null>(null)
const listLoading = ref(false), quoteLoading = ref(false), busy = ref(false), error = ref(''), quoteError = ref(''), submitError = ref(''), uncertain = ref(false), frozen = ref<PurchaseIdentity | null>(null)
const matched = computed(() => frozen.value ? rows.value.find(p => p.identity.clientRequestId === frozen.value?.clientRequestId) : undefined)
let listController: AbortController | undefined, quoteController: AbortController | undefined
async function load() { listController?.abort(); const current = listController = new AbortController(); listLoading.value = true; error.value = ''; try { const [p, po] = await Promise.all([products(current.signal), purchases(current.signal)]); if (!current.signal.aborted) { list.value = p; rows.value = po } } catch (e) { if (!current.signal.aborted) error.value = (e as Error).message } finally { if (listController === current) listLoading.value = false } }
async function getQuote() { quoteController?.abort(); quoteError.value = ''; currentQuote.value = null; if (!skuValid(sku.value)) { quoteError.value = 'SKU 限 1–64 個英文字母、數字、底線或連字號。'; return } const current = quoteController = new AbortController(); quoteLoading.value = true; try { const result = await quote(provider.value, sku.value, current.signal); if (!current.signal.aborted) { currentQuote.value = result; unitPrice.value = result.unitPrice } } catch (e) { if (!current.signal.aborted) quoteError.value = (e as Error).message } finally { if (quoteController === current) quoteLoading.value = false } }
watch([provider, sku], () => { quoteController?.abort(); currentQuote.value = null; quoteError.value = '' });
async function submit() { if (busy.value || frozen.value) return; submitError.value = ''; if (!selected.value || !skuValid(sku.value) || !positiveInt(quantity.value) || !moneyValid(unitPrice.value)) { submitError.value = '請選商品，並確認 SKU、正整數數量與最多兩位小數的非負單價。'; return } try { frozen.value = { clientRequestId: newId(), productId: selected.value, supplierSku: sku.value, quantity: quantity.value, unitPrice: unitPrice.value, currency: 'TWD', provider: provider.value } } catch (e) { submitError.value = (e as Error).message; return } busy.value = true; try { const result = await createPurchase(frozen.value); router.push(`/procurement/${result.id}`) } catch (e) { submitError.value = (e as Error).message; uncertain.value = e instanceof ApiError && e.uncertain } finally { busy.value = false } }
function newDraft() { if (busy.value) return; frozen.value = null; uncertain.value = false; submitError.value = '' }
onMounted(load); onUnmounted(() => { listController?.abort(); quoteController?.abort() })
</script>
<template><div class="page"><div class="page-heading"><div><span class="eyebrow accent">PROCUREMENT</span><h1>採購與收貨</h1><p>查詢供應商報價、建立採購單，並追蹤實際收貨。</p></div><button class="button button-secondary" type="button" :disabled="listLoading" @click="load">更新資料</button></div>
  <div class="two-column"><section class="panel"><span class="eyebrow accent">01 / SUPPLIER QUOTE</span><h2>供應商報價</h2><div class="field-pair"><div class="field"><label for="quote-provider">供應商路徑</label><select id="quote-provider" v-model="provider" :disabled="!!frozen"><option value="direct">direct</option><option value="wiremock">wiremock</option><option value="microcks">microcks</option></select></div><div class="field"><label for="quote-sku">供應商 SKU</label><input id="quote-sku" v-model.trim="sku" maxlength="64" :disabled="!!frozen" /></div></div><p class="hint">範例：REAL-001、MOCK-001、DENY-001。報價僅供參考，送單前請核對價格。</p><button class="button button-secondary" type="button" :disabled="quoteLoading || !skuValid(sku)" @click="getQuote">{{ quoteLoading ? '查詢中…' : '查詢報價' }}</button><p v-if="quoteError" class="notice error" role="alert">{{ quoteError }} <button type="button" @click="getQuote">重試</button></p><div v-if="currentQuote" class="quote-result" role="status"><span class="eyebrow">SUPPLIER RESPONSE</span><strong>{{ currentQuote.name }}</strong><p>{{ currentQuote.sku }} · {{ currentQuote.origin }}</p><b>{{ currentQuote.currency }} {{ currentQuote.unitPrice }}</b></div></section>
    <section class="panel"><span class="eyebrow accent">02 / NEW PURCHASE</span><h2>建立採購單</h2><form @submit.prevent="submit"><label for="purchase-product">對應商品</label><select id="purchase-product" v-model="selected" :disabled="!!frozen"><option value="">請選擇商品</option><option v-for="p in list" :key="p.id" :value="p.id">{{ p.name }} · {{ p.id.slice(0, 8) }}</option></select><div class="field-pair"><div class="field"><label for="purchase-qty">採購數量</label><input id="purchase-qty" v-model.number="quantity" type="number" min="1" max="2147483647" step="1" required :disabled="!!frozen"/></div><div class="field"><label for="purchase-price">單價（TWD）</label><input id="purchase-price" v-model.number="unitPrice" type="number" min="0" step="0.01" required :disabled="!!frozen"/></div></div><p class="hint">供應商接受採購不會直接增加庫存；實際收貨另行登錄。</p><p v-if="frozen" class="notice warning" role="status">本次 clientRequestId：<code>{{ frozen.clientRequestId }}</code>。身分已固定，請查核結果後再開新草稿。<template v-if="matched"><br>最近清單找到此身分：<RouterLink :to="`/procurement/${matched.id}`" class="text-link">查看採購單 →</RouterLink></template><template v-else><br>可更新最近 100 筆清單，依本次身分查核。</template></p><p v-if="submitError" class="notice" :class="uncertain ? 'warning' : 'error'" role="alert">{{ submitError }}{{ uncertain ? ' 結果未確認；不要直接重送。' : '' }}</p><button class="button button-primary full" type="submit" :disabled="busy || !!frozen || !selected || !positiveInt(quantity) || !moneyValid(unitPrice)">{{ busy ? '送出中…' : '建立採購單' }}</button><button v-if="frozen" class="button button-secondary full" type="button" :disabled="busy" @click="newDraft">已查核，建立新草稿</button></form></section></div>
  <section class="panel list-panel"><div class="panel-heading"><div><span class="eyebrow accent">RECENT PURCHASES</span><h2>最近 100 筆採購單</h2></div><span class="result-count">{{ listLoading ? '讀取中…' : `${rows.length} 筆已讀取` }}</span></div><p v-if="error" class="notice error" role="alert">{{ error }} <button type="button" @click="load">重試</button></p><p v-else-if="listLoading" class="empty-state" role="status">正在讀取採購資料…</p><p v-else-if="!rows.length" class="empty-state">目前沒有採購單。建立後會顯示在這裡。</p><div v-else class="table-wrap"><table><thead><tr><th>採購單</th><th>供應商 / SKU</th><th>數量 / 單價</th><th>狀態</th><th></th></tr></thead><tbody><tr v-for="p in rows" :key="p.id"><td><code>{{ p.id.slice(0, 8) }}…</code></td><td>{{ p.identity.provider }} / {{ p.identity.supplierSku }}</td><td>{{ p.identity.quantity }} 件 · {{ money(p.identity.unitPrice) }}</td><td><span class="status-pill">{{ p.state }}</span></td><td><RouterLink :to="`/procurement/${p.id}`" class="text-link">查看 →</RouterLink></td></tr></tbody></table></div></section>
</div></template>
