<script setup lang="ts">
import { computed, onMounted, onUnmounted, ref, watch } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { ApiError, createOrder, money, newId, positiveInt, product, uuidValid, type Product } from '../api'
const route = useRoute(), router = useRouter()
const item = ref<Product | null>(null), quantity = ref(1), loading = ref(false), busy = ref(false), error = ref(''), submitError = ref(''), uncertain = ref(false), operationId = ref(''), successId = ref('')
let controller: AbortController | undefined
async function load() { controller?.abort(); const current = controller = new AbortController(); item.value = null; error.value = ''; if (!uuidValid(String(route.params.id))) { error.value = '商品 ID 格式不正確。'; return } loading.value = true; try { const result = await product(String(route.params.id), current.signal); if (!current.signal.aborted) item.value = result } catch (e) { if (!current.signal.aborted) error.value = (e as Error).message } finally { if (controller === current) loading.value = false } }
const total = computed(() => item.value ? Math.round(item.value.price * quantity.value * 100) / 100 : 0)
async function submit() { if (busy.value || !item.value || uncertain.value || successId.value) return; submitError.value = ''; if (!positiveInt(quantity.value)) { submitError.value = '數量須為 1 至 2,147,483,647 的整數。'; return } busy.value = true; try { operationId.value = newId(); const result = await createOrder({ product: item.value, quantity: quantity.value, operationId: operationId.value }); successId.value = result.value.orderId; router.push(`/orders/${result.value.orderId}`) } catch (e) { submitError.value = (e as Error).message; uncertain.value = e instanceof ApiError && e.uncertain } finally { busy.value = false } }
function newAttempt() { if (busy.value) return; uncertain.value = false; operationId.value = ''; submitError.value = '已選擇建立新嘗試。先以原作業 ID 查核，避免重複下單。' }
watch(() => route.params.id, load); onMounted(load); onUnmounted(() => controller?.abort())
</script>
<template><div class="page"><RouterLink to="/products" class="back-link">← 返回商品查詢</RouterLink><div class="page-heading"><div><span class="eyebrow accent">PRODUCT DETAIL</span><h1>商品與銷售下單</h1><p>確認服務回傳的商品資料與數量，再建立單品訂單。</p></div></div>
  <p v-if="error" class="notice error" role="alert">{{ error }} <button type="button" @click="load">重試</button></p><p v-else-if="loading" class="panel empty-state" role="status">正在讀取商品…</p>
  <div v-else-if="item" class="detail-grid"><section class="panel product-card"><div class="product-symbol" aria-hidden="true"><svg viewBox="0 0 64 64"><path d="M9 20 32 8l23 12v25L32 57 9 45zM9 20l23 12 23-12M32 32v25"/></svg></div><span class="eyebrow accent">商品資訊</span><h2>{{ item.name }}</h2><p>{{ item.description || '此商品沒有描述。' }}</p><div class="info-row"><span>商品 ID</span><code>{{ item.id }}</code></div><div class="info-row"><span>單價</span><strong>{{ money(item.price) }}</strong></div></section>
    <section class="panel order-card"><span class="eyebrow accent">NEW SALES ORDER</span><h2>建立銷售訂單</h2><p class="muted">商品與價格採用這次讀取的快照；送出後請依訂單 ID 查核。</p><form @submit.prevent="submit"><label for="order-qty">訂購數量</label><input id="order-qty" v-model.number="quantity" type="number" min="1" max="2147483647" step="1" required :disabled="busy || uncertain"/><div class="total-row"><span>預計金額</span><strong>{{ money(total) }}</strong></div><p v-if="submitError" class="notice" :class="uncertain ? 'warning' : 'error'" role="alert">{{ submitError }}<template v-if="uncertain"><br>本次作業 ID：<code>{{ operationId }}</code>。請查詢系統資料後再決定是否建立新嘗試。</template></p><button class="button button-primary full" type="submit" :disabled="busy || uncertain || !!successId || !positiveInt(quantity)">{{ busy ? '送出中…' : '確認建立訂單' }}</button><button v-if="uncertain" class="button button-secondary full" type="button" @click="newAttempt">我已查核，建立新的嘗試</button></form></section></div>
</div></template>
