<script setup lang="ts">
import { computed, onMounted, onUnmounted, ref, watch } from 'vue'
import { useRoute } from 'vue-router'
import { ApiError, dateTime, money, newId, positiveInt, purchase, receive, reconcile, uuidValid, type PurchaseOrder } from '../api'
const route = useRoute(), item = ref<PurchaseOrder | null>(null), loading = ref(false), busy = ref(false), error = ref(''), actionError = ref(''), message = ref(''), receiptQuantity = ref(1)
const pendingReceipt = ref<{ orderId: string; id: string; quantity: number; checked: boolean } | null>(null), receiptUnknown = ref(false), reconcileUnknown = ref(false)
const remaining = computed(() => item.value ? item.value.identity.quantity - item.value.receivedQuantity : 0)
const canReceive = computed(() => item.value && ['Accepted','PartiallyReceived'].includes(item.value.state) && remaining.value > 0)
let controller: AbortController | undefined
async function load(allowDuringMutation = false) { if (busy.value && !allowDuringMutation) return; controller?.abort(); item.value = null; error.value = ''; const orderId = String(route.params.id); if (!uuidValid(orderId)) { error.value = '採購單 ID 格式不正確。'; loading.value = false; return } const current = controller = new AbortController(); loading.value = true; try { const result = await purchase(orderId, current.signal); if (!current.signal.aborted && String(route.params.id) === orderId) { item.value = result; resolveReceipt(result) } } catch (e) { if (!current.signal.aborted && String(route.params.id) === orderId) error.value = (e as Error).message } finally { if (controller === current) loading.value = false } }
function resolveReceipt(result: PurchaseOrder) { if (!pendingReceipt.value || pendingReceipt.value.orderId !== result.id) return; if (result.receipts.some(r => r.receiptId === pendingReceipt.value?.id && r.quantity === pendingReceipt.value?.quantity)) { message.value = '服務已確認這筆收貨紀錄。'; pendingReceipt.value = null; receiptUnknown.value = false } else if (receiptUnknown.value) pendingReceipt.value.checked = true }
async function checkReceipt() { if (busy.value || !pendingReceipt.value || pendingReceipt.value.orderId !== String(route.params.id)) return; controller?.abort(); const orderId = pendingReceipt.value.orderId; const current = controller = new AbortController(); loading.value = true; actionError.value = ''; try { const result = await purchase(orderId, current.signal); if (!current.signal.aborted && String(route.params.id) === orderId) { item.value = result; resolveReceipt(result); if (pendingReceipt.value) message.value = '目前快照未見這筆收貨。若要重送，僅能使用同一 receiptId 與數量。' } } catch (e) { if (!current.signal.aborted && String(route.params.id) === orderId) actionError.value = (e as Error).message } finally { if (controller === current) loading.value = false } }
async function doReconcile() { if (busy.value || !item.value) return; controller?.abort(); const orderId = item.value.id; busy.value = true; actionError.value = ''; message.value = ''; try { const result = await reconcile(orderId); if (String(route.params.id) === orderId) { item.value = result; reconcileUnknown.value = ['PendingSubmission','SubmissionUnknown'].includes(result.state); message.value = reconcileUnknown.value ? '供應商結果仍待確認，請稍後重新查詢。' : '已讀回最新採購狀態。' } } catch (e) { if (String(route.params.id) === orderId) { actionError.value = (e as Error).message; reconcileUnknown.value = e instanceof ApiError && e.uncertain } } finally { busy.value = false } }
async function doReceive(retry = false) { if (busy.value || !item.value || !canReceive.value) return; const orderId = item.value.id; actionError.value = ''; message.value = ''; if (retry && (!pendingReceipt.value || !pendingReceipt.value.checked || pendingReceipt.value.orderId !== orderId)) return; if (!retry && (!positiveInt(receiptQuantity.value) || receiptQuantity.value > remaining.value)) { actionError.value = `數量須為 1 至剩餘 ${remaining.value} 件。`; return } try { if (!retry) pendingReceipt.value = { orderId, id: newId(), quantity: receiptQuantity.value, checked: false } } catch (e) { actionError.value = (e as Error).message; return } const receipt = pendingReceipt.value!; controller?.abort(); busy.value = true; try { const result = await receive(orderId, receipt.id, receipt.quantity); if (String(route.params.id) === orderId) { item.value = result.order; pendingReceipt.value = null; receiptUnknown.value = false; message.value = result.created ? '實際收貨已登錄。' : '服務確認這筆收貨已存在。' } } catch (e) { if (String(route.params.id) === orderId) { actionError.value = (e as Error).message; receiptUnknown.value = e instanceof ApiError && e.uncertain; if (!receiptUnknown.value) pendingReceipt.value = null } } finally { busy.value = false } }
watch(() => route.params.id, () => { controller?.abort(); pendingReceipt.value = null; receiptUnknown.value = false; actionError.value = ''; message.value = ''; load(true) }); onMounted(load); onUnmounted(() => controller?.abort())
</script>
<template><div class="page"><RouterLink to="/procurement" class="back-link">← 返回採購與收貨</RouterLink><div class="page-heading"><div><span class="eyebrow accent">PURCHASE ORDER</span><h1>採購單明細</h1><p>以服務回傳的採購狀態與收貨紀錄為準。</p></div><button class="button button-secondary" type="button" :disabled="loading || busy" @click="load()">重新查詢</button></div>
  <p v-if="error" class="notice error" role="alert">{{ error }} <button type="button" @click="load()">重試</button></p><p v-else-if="loading && !item" class="panel empty-state" role="status">正在查詢採購單…</p>
  <template v-if="item"><section class="panel purchase-overview"><div class="panel-heading"><div><span class="eyebrow accent">CURRENT RECORD</span><h2>採購資訊</h2><code>{{ item.id }}</code></div><span class="status-pill large">{{ item.state }}</span></div><div class="fact-grid"><div><span>供應商路徑</span><strong>{{ item.identity.provider }}</strong></div><div><span>供應商 SKU</span><strong>{{ item.identity.supplierSku }}</strong></div><div><span>採購數量</span><strong>{{ item.identity.quantity }} 件</strong></div><div><span>單價</span><strong>{{ money(item.identity.unitPrice) }}</strong></div><div><span>已收 / 待收</span><strong>{{ item.receivedQuantity }} / {{ remaining }} 件</strong></div><div><span>供應商訂單 ID</span><strong>{{ item.supplierOrderId || '尚未提供' }}</strong></div></div><div class="meta-grid"><div>商品 ID <code>{{ item.identity.productId }}</code></div><div>Client Request ID <code>{{ item.identity.clientRequestId }}</code></div><div>建立 {{ dateTime(item.createdAt) }}</div><div>更新 {{ dateTime(item.updatedAt) }}</div></div></section>
    <div class="two-column"><section class="panel"><span class="eyebrow accent">SUPPLIER STATUS</span><h2>結果協調</h2><p class="muted">送單結果待確認時，依原 clientRequestId 向供應商查核。此動作不建立新採購。</p><p v-if="['PendingSubmission','SubmissionUnknown'].includes(item.state)" class="notice warning">目前結果仍未確定。請使用協調或重新查詢。</p><button class="button button-secondary full" type="button" :disabled="busy || !['PendingSubmission','SubmissionUnknown'].includes(item.state)" @click="doReconcile">{{ busy ? '處理中…' : '協調供應商結果' }}</button></section>
      <section class="panel"><span class="eyebrow accent">PHYSICAL RECEIPT</span><h2>登錄實際收貨</h2><p class="muted">只在供應商已接受後登錄到貨；庫存後續變動由既有服務處理。</p><form @submit.prevent="doReceive(false)"><label for="receipt-qty">本次收貨數量</label><input id="receipt-qty" v-model.number="receiptQuantity" type="number" min="1" :max="remaining" step="1" required :disabled="busy || receiptUnknown || !canReceive"/><p class="hint">目前尚可收 {{ remaining }} 件。</p><button class="button button-primary full" type="submit" :disabled="busy || receiptUnknown || !canReceive || !positiveInt(receiptQuantity) || receiptQuantity > remaining">{{ busy ? '送出中…' : '確認實際收貨' }}</button></form><div v-if="receiptUnknown && pendingReceipt" class="notice warning" role="alert"><strong>收貨結果尚未確認</strong><p>Receipt ID：<code>{{ pendingReceipt.id }}</code><br>數量：{{ pendingReceipt.quantity }} 件。請先讀回收貨紀錄。</p><button class="button button-secondary" type="button" :disabled="loading || busy" @click="checkReceipt">讀回收貨紀錄</button><button v-if="pendingReceipt.checked" class="button button-secondary" type="button" :disabled="busy || !canReceive || pendingReceipt.quantity > remaining" @click="doReceive(true)">以相同 ID 重送</button></div></section></div>
    <p v-if="actionError" class="notice error" role="alert">{{ actionError }}</p><p v-if="message" class="notice success" role="status">{{ message }}</p>
    <section class="panel list-panel"><div class="panel-heading"><div><span class="eyebrow accent">RECEIPT HISTORY</span><h2>實際收貨紀錄</h2></div><span class="result-count">{{ item.receipts.length }} 筆</span></div><p v-if="!item.receipts.length" class="empty-state">尚無實際收貨紀錄。供應商接受訂單本身不代表已入庫。</p><div v-else class="table-wrap"><table><thead><tr><th>Receipt ID</th><th>數量</th><th>收貨時間</th></tr></thead><tbody><tr v-for="r in item.receipts" :key="r.receiptId"><td><code>{{ r.receiptId }}</code></td><td>{{ r.quantity }} 件</td><td>{{ dateTime(r.receivedAt) }}</td></tr></tbody></table></div></section>
  </template></div></template>
